---
title: "Charge hierarchy creation"
output: html_notebook
---

# Libraries
```{r}
library(data.table)
library(openxlsx)
library(readxl)
library(lubridate)
library(tidyverse)
library(XML)
library(xml2)
library(xmltools)
library(fuzzyjoin)
library(gsubfn)

```


# Charge Hierarchy Creation

2020 DOJ Hierarchies
```{r}

doj_hierarchy_2020 <- fread("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/Master Charge Code Table 2020.csv")
doj_hierarchy_2020_jbsis <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/2020_March04_DOJ_Offense_Table_JBSIS.xlsx")


names(doj_hierarchy_2020) <- c("summary_code", "bcs_code", "hierarchy", "charge_level", "charge", "charge_code", "master_charge_description", "sentence")
names(doj_hierarchy_2020_jbsis) <- c("summary_code", "cjis_code", "hierarchy", "charge_level", "charge", "charge_code", "master_charge_description", "sentence", "jbsis_code")

doj_hierarchy_2020 <- left_join(doj_hierarchy_2020, doj_hierarchy_2020_jbsis)

doj_hierarchy_2020 <- doj_hierarchy_2020 %>%
  mutate(charge_level = toupper(charge_level),
         charge_level = if_else(!charge_level %in% c("F", "I", "M"), "Other", charge_level),
         charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}|EX|\\+|","", charge)),
         charge_code = if_else(!charge_code %in% c("PC", "VC", "HS", "BP", "WI", "US"), "Other", charge_code)) %>%
  distinct(charge, charge_code, charge_level, .keep_all = T) %>%
  unite(join_var, charge_level, charge_code, charge, remove = F) %>%
  select(join_var, master_charge_description, hierarchy, charge_level, charge_code, charge, jbsis_code, summary_code, bcs_code) %>%
  mutate(summary_code = as.numeric(summary_code),
         bcs_code = as.numeric(bcs_code))


```


2017 DOJ Hierarchies
```{r}
#this one does not have summary codes. It does have BCS codes, could maybe convert them


doj_hierarchy_2017 <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/dojoffenses.xls")

doj_hierarchy_2017 <- doj_hierarchy_2017 %>%
  mutate(STATUTE2 = gsub("\\/|\\(|\\)| |\\.|\\.*","", STATUTE2)) %>%
  unite("charge",STATUTE1,STATUTE2, sep = "") %>%
  mutate(charge = gsub("NA", "", charge)) %>%
  select(charge, master_charge_description = DESCRIPTION, hierarchy = HIERARCHY, charge_code = CODE_TYPE, charge_level = CHARGE_TYPE, bcs_code = BCS_CODE) %>%
  filter(!is.na(hierarchy)) %>%
  # mutate(charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}","", charge))) %>%
  mutate(charge_level = if_else(!charge_level %in% c("F", "I", "M"), "Other", charge_level),
         charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}|EX|\\+|","", charge)),
         charge_code = if_else(!charge_code %in% c("PC", "VC", "HS", "BP", "WI", "US"), "Other", charge_code)) %>%
  # mutate(charge_level = fct_collapse(charge_level, O = c("S", "X"))) %>% #Incorretly labeled, juvenile, and miscelanious 
  distinct(charge, charge_code, charge_level, .keep_all = T) %>%
  unite(join_var, charge_level, charge_code, charge, remove = F) %>%
  select(join_var, master_charge_description, hierarchy, charge_level, charge_code, charge, bcs_code)%>%
  mutate(bcs_code = as.numeric(bcs_code))



```


2008 DOJ Hierarchies
```{r}
#DOJ Crime Severity Ratings 2008
doj_hierarchy_2008 <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/DOJ Crime Severity Ratings May 2008.xls", col_names = FALSE, skip = 11)

#Recreating Variables
names(doj_hierarchy_2008) <- c("summary_code", "bcs_code", "hierarchy", "charge_level", "charge", "charge_code", "master_charge_description", "sentence")

#collapsed codes for merger with Fresno
doj_hierarchy_2008 <- doj_hierarchy_2008 %>% 
  # mutate(charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}","", charge))) %>%
  mutate(charge_level = strapplyc(charge_level, "^(.).*", simplify = T)) %>%
  mutate(charge_level = if_else(!charge_level %in% c("F", "I", "M"), "Other", charge_level),
         charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}|EX|\\+|","", charge)),
         charge_code = if_else(!charge_code %in% c("PC", "VC", "HS", "BP", "WI", "US"), "Other", charge_code)) %>%
  filter(!is.na(hierarchy)) %>%
  # mutate(charge_level = fct_recode(charge_level, "Other" = "S")) %>%
  distinct(charge_level, charge_code, charge, .keep_all = T)  %>%
  unite(join_var, charge_level, charge_code, charge, remove = F) %>%
  select(join_var, master_charge_description, hierarchy, charge_level, charge_code, charge, summary_code, bcs_code)%>%
  mutate(summary_code = as.numeric(summary_code),
         bcs_code = as.numeric(bcs_code))
 
```


 Charge Code Table 
```{r}
#--This chunk pulls the master charge code table and standardizes it. 
mcct_2016 <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/Master Charge Code Table 2016.xlsx", guess_max = Inf)

mcct_2016 <- mcct_2016 %>%
  filter(!is.na(`CalDOJ HIERARCHY Code Informational only`))

mcct_2016 <- mcct_2016 %>% 
  select(charge_code = CODE, 
         charge = `CODE SECTION (upper/lower case)`, 
         hierarchy = `CalDOJ HIERARCHY Code Informational only`,
         master_charge_description = `Offense Display (For AJIS and ISAB Departments)`,
         charge_level = LEVEL,
         summary_code = `CalDOJ Summary Code`,
         bcs_code = `CalDOJ BCS Code Informational only`) %>%
  # mutate(charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}","", charge))) %>%
  mutate(charge_level = if_else(!charge_level %in% c("F", "I", "M"), "Other", charge_level),
         charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}|EX|\\+|","", charge)),
         charge_code = if_else(!charge_code %in% c("PC", "VC", "HS", "BP", "WI", "US"), "Other", charge_code)) %>%
  distinct(charge_level, charge_code, charge, .keep_all = T) %>%
  mutate(hierarchy = as.numeric(hierarchy)) %>%
  unite(join_var, charge_level, charge_code, charge, remove = F) %>%
  select(join_var, master_charge_description, hierarchy, charge_level, charge_code, charge, summary_code, bcs_code)%>%
  mutate(summary_code = as.numeric(summary_code),
         bcs_code = as.numeric(bcs_code))
```


JBSIS Hierarchies
```{r}
#JBSIS matched Charges
charge_hier_jbsis <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/Copy of 2016_Nov21_DOJ_Offense_Table_JBSIS.xlsx") 

names(charge_hier_jbsis) <- toupper(names(charge_hier_jbsis))

charge_hier_jbsis <- charge_hier_jbsis %>% 
  select(charge = `CODE SECTION`,
         charge_code = `CODE TYPE`,
         master_charge_description = `OFFENSE DESCRIPTION`,
         charge_level = `OFF LEVEL`,
         hierarchy = HIERARCHY,
         summary_code = `SUM CODE`,
         bcs_code = `BCS CODE`) %>%
  # mutate(charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*","", charge))) %>% 
  mutate(charge_level = if_else(!charge_level %in% c("F", "I", "M"), "Other", charge_level),
         charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}|EX|\\+|","", charge)),
         charge_code = if_else(!charge_code %in% c("PC", "VC", "HS", "BP", "WI", "US"), "Other", charge_code)) %>%
  distinct(charge, charge_code, charge_level, .keep_all = T) %>%
  unite(join_var, charge_level, charge_code, charge, remove = F) %>%
  select(join_var, master_charge_description, hierarchy, charge_level, charge_code, charge, summary_code, bcs_code)%>%
  mutate(summary_code = as.numeric(summary_code),
         bcs_code = as.numeric(bcs_code))
```

Special Allegations--Hierarchies are Max
```{r}
#these have no summary codes or bcs codes

charge_hier_special <- fread("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/San_Mateo_Qualifier_Flags_Court_charges.csv", header = T)
charge_hier_special2 <- fread("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/Yuba_Qualifier_Flags_Court_charges.csv", header = T)
charge_hier_special3 <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/qualifier_codes_for_Noah_Kings_Court.xlsx")
charge_hier_special4 <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/qualifier_codes_for_Noah_Napa_Court.xlsx")
charge_hier_special5 <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/qualifier_codes_for_Noah_Sonoma_Court.xlsx")

charge_hier_special6 <- tibble(join_var = c("M_VC_23578", "M_VC_231035", "F_PC_117012C1", "F_PC_120225A", "F_PC_1170H3", "F_PC_1170H", 
                                               "F_PC_120227A", "F_PC_120221", "F_PC_667A1", "F_PC_12022A1", "F_PC_12022B1", 
                                               "F_VC_23577", "F_PC_1202253C", "F_PC_290018BZ", "F_PC_1202253B", 
                                               "F_PC_6676D", "F_PC_1202253D", "F_PC_1203K", "F_HS_113702A", "F_PC_120307A11", 
                                               "F_HS_11370A", "F_PC_6675C21", "F_PC_667E1", "F_PC_6676C", "F_PC_120306A1", "F_PC_969F", 
                                               "F_PC_120306A1", "F_PC_1170H5B", "F_PC_1170H5A")) %>%
  separate(join_var, c("court_charge_level", "court_charge_code", "court_charge"))


charge_hier_special <- bind_rows(charge_hier_special, charge_hier_special2, charge_hier_special3, charge_hier_special4, charge_hier_special5, charge_hier_special6) 

rm(charge_hier_special2, charge_hier_special3, charge_hier_special4, charge_hier_special5, charge_hier_special6)

charge_hier_special <- charge_hier_special %>%
  select(charge_code = court_charge_code, charge_level = court_charge_level, charge = court_charge, master_charge_description = court_charge_description) %>%
  mutate(charge_level = if_else(!charge_level %in% c("F", "I", "M"), "Other", charge_level),
         charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}|EX|\\+|","", charge)),
         charge_code = if_else(!charge_code %in% c("PC", "VC", "HS", "BP", "WI", "US"), "Other", charge_code)) %>%
  mutate(master_charge_description = gsub("^.*-", "", toupper(master_charge_description))) %>%
  group_by(charge_code, charge) %>% 
  mutate(master_charge_description = if_else(is.na(master_charge_description), max(master_charge_description, na.rm = T), master_charge_description)) %>%
  ungroup() %>%
  distinct(charge, charge_code, charge_level, .keep_all = T) %>%
  unite(join_var, charge_level, charge_code, charge, remove = F) %>%
  mutate(hierarchy = 1e6) %>%
  select(join_var, master_charge_description, hierarchy, charge_level, charge_code, charge) %>%
  mutate(special_flag = 1) 

# charge_hier_special %>%
#   filter(grepl("23578", join_var)) %>%
#   group_by(charge_code, charge) %>%
#   mutate(master_charge_description = if_else(is.na(master_charge_description), max(master_charge_description, na.rm = T), master_charge_description))
```

  -New Special Allegations
```{r}  
#   
# charge_hier_check <- tibble(join_var = c("M_VC_23578", "M_VC_231035", "F_PC_117012C1", "F_PC_120225A", "F_PC_1170H3", "F_PC_1170H", 
#                                                "F_PC_120227A", "F_PC_120221", "F_PC_667A1", "F_PC_667A1", "F_PC_12022A1", "F_PC_12022B1", 
#                                                "F_VC_23577", "F_PC_1202253C", "F_PC_290018BZ", "F_PC_290018BZ", "F_PC_1202253B", 
#                                                "F_PC_6676D", "F_PC_1202253D", "F_PC_1203K", "F_HS_113702A", "F_PC_120307A11", 
#                                                "F_HS_11370A", "F_PC_6675C21"))
# anti_join(charge_hier_check, charge_hier_special)
```

Missing Charges
```{r}
#these have no summary codes or bcs codes

charge_hier_missing <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/Charges Missing from the Charge Code Tables original.xlsx", sheet = "Combined") 

charge_hier_missing <- charge_hier_missing %>% 
  mutate(charge_level = if_else(!charge_level %in% c("F", "I", "M"), "Other", charge_level),
         charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}|EX|\\+|","", charge)),
         charge_code = if_else(!charge_code %in% c("PC", "VC", "HS", "BP", "WI", "US"), "Other", charge_code)) %>%
  distinct(charge, charge_code, charge_level, .keep_all = T) %>%
  unite(join_var, charge_level, charge_code, charge, remove = F) %>%
  select(join_var, master_charge_description, hierarchy, charge_level, charge_code, charge) 
```




Merging hiearchies 
```{r}
charge_hier <- bind_rows(doj_hierarchy_2020, doj_hierarchy_2017, doj_hierarchy_2008, mcct_2016, charge_hier_jbsis, charge_hier_special, charge_hier_missing) 

#fill in summary codes using bcs codes when possible and unambiguous

#map all combinations of summary code and bcs code found in the combined hierarchies
bcs <- charge_hier %>%
  select(summary_code, bcs_code) %>%
  distinct()

#remove any bcs codes that map onto more than one non-null summary code
bcs<- bcs %>%
  filter(!is.na(summary_code)) %>%
  arrange(bcs_code) %>%
  add_count(bcs_code) %>%
  filter(n==1) %>%
  select(-n)

#use bcs codes to match summary codes and use them when the original summary code was missing. this reduces the missing summary codes by about half
charge_hier <- charge_hier %>%
  left_join(bcs, by = 'bcs_code') %>%
  mutate(summary_code = if_else(!is.na(summary_code.x), summary_code.x, summary_code.y)) %>%
  select(-summary_code.x, -summary_code.y)

charge_hier <- charge_hier %>%
  mutate(special_flag = if_else(is.na(special_flag), 0, special_flag),
         summary_code = if_else(is.na(summary_code), 1000, summary_code)) %>%
  group_by(join_var) %>%
  mutate(special_flag = max(special_flag)) %>%
  #fill in missing summary codes
  mutate(summary_code = min(summary_code)) %>%
  ungroup() %>%
  distinct(join_var, .keep_all = T) %>%
  mutate(hierarchy = if_else(is.na(hierarchy|hierarchy >= 3e5|hierarchy < 1000), 1e6, hierarchy))

save(charge_hier, file = "Complete Charge Code Hierarchy_SL.RData")
# shell.exec(getwd())


load("G:/CrimJustice/PretrialAssessmentPilot/Complete Charge Code Hierarchy.RData")
charge_hier %>%
  filter(grepl("286", charge))
```


# Charge Hierarchy Flag Adds
```{r}
load("Complete Charge Code Hierarchy_SL.RData")

#Serious and Violent Felonies
serious_violent_charges <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/Serious and Violent Charges.xlsx", 
    sheet = "Data") %>%
  # filter(Serious == T | Violent == T)
  select(charge, charge_level, serious_felony_flag = Serious, violent_felony_flag = Violent) %>%
  filter(serious_felony_flag == 1 | violent_felony_flag == 1, charge_level == "F") %>%
  mutate(charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|\\\\.*|\\{o|\\}","", charge))) %>%
  mutate(charge = gsub("HSC", "HS_", charge),
         charge = gsub("PEN", "PC_", charge),
         charge = gsub("VEH", "VC_", charge)) %>%
  unite(join_var, charge_level, charge) %>%
  mutate(serious_violent_flag = if_else(serious_felony_flag == T|violent_felony_flag == T, 1, 0)) %>%
  # mutate(serious_felony_flag = if_else(serious_felony_flag == T, 1, 0),
  #        violent_felony_flag = if_else(violent_felony_flag == T, 1, 0)) %>%
  mutate_all(funs(ifelse(is.na(.), 0, .))) %>%
  distinct(join_var, .keep_all = T) %>%
  ungroup()

charge_hier <- charge_hier %>%
  left_join(serious_violent_charges) %>%
  mutate(serious_violent_flag = if_else(is.na(serious_violent_flag), 0, serious_violent_flag)) 
  # mutate_at(vars(serious_felony_flag, violent_felony_flag), funs(if_else(is.na(.), 0, .)))

rm(serious_violent_charges)

#Pretrial Violent Charges
pretrial_violent <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/Pretrial Pilot Consensus on Violent Offense List - FINAL 2-3-20.xlsx")

names(pretrial_violent) <- c("charge", "violent_description", "violent_psa_flag")

pretrial_violent <- pretrial_violent %>%
  mutate(violent_psa_flag = 1,
         charge_code = if_else(grepl("Veh Code", charge), "VC", "PC"),
         charge = gsub("\\/|\\(|\\)| |\\.|\\.*|\\\\.*|\\{|\\}|^[A-Z]* [A-Z]* ","", toupper(charge))) %>%
  select(-violent_description)

charge_hier <- left_join(charge_hier, pretrial_violent) %>%
  mutate(violent_psa_flag = if_else(is.na(violent_psa_flag), 0, violent_psa_flag))


# Charge Flags Added--Needs fixing
charge_hier <- charge_hier %>%
  mutate(capital_flag = if_else(charge_code == "PC" & charge %in% c("37", "128", "206", "2095", "218", "2361C2", "273AB"), 1, 0),
         dv_flag = if_else(grepl("DOMESTIC|SPOUSE|PARTNER|COHABITANT", master_charge_description) &
                             !grepl("MARRY|CRT ORD|COURT ORDER|FOREIGN|LAND|FAIL|SHELTER", master_charge_description), 1, 0),
         #Attach Flags DV and Sup Vio Flags #Sup Vio Based on Charge Descriptions--Including Flash Incarceration
         sup_vio_flag = if_else((grepl("^SUP| SUP |SUPERVISION|PROBATION|PAROLE", master_charge_description) &
                                  !grepl("^AGG ARSON|SUPV/ETC PROSTITUTION|MENTALY DISORDERD|^SEXUAL ACTIVITY|^SUPPLY|^ADL|SEX|TRANSFER|PROSTITUTION",
                                         master_charge_description))| charge %in% c("3454", "3455", "12032", "12032A"), 1, 0),
         fta_flag = if_else(grepl("APPEAR|FTA", master_charge_description) & !grepl("^DEMAND|WITNESS", master_charge_description), 1, 0),
         marijuana_flag = if_else(grepl("MARIJ|CANNA", master_charge_description), 1, 0),
         sex_flag = if_else(grepl("SEX|COPULATION|RAPE|ORAL|PENETRATION|MOLLEST|LASCIVIOUS|INCEST", 
                                  master_charge_description)|(charge_code == "PC" & charge %in% c("2434", "2641", "266H", "266I", "266J", "269", "272", "285", "286", "288",
                                                           "288a", "2882", "2884", "2885", "2887", "289", "3111", "31111", "314",
                                                           "6476", "653FC")), 1, 0),
         sb10_sex_flag = if_else(sex_flag == 1, 1, 0),
         dui_flag = if_else((charge_code == "VC" & charge %in% c("23546", "23153", "23578"))|(charge_code == "PC" & charge == "1915B"), 1, 0),
         sb10_dui_flag = if_else((charge_code == "VC" & charge %in% c("23546", "23153", "23578"))|(charge_code == "PC" & charge == "1915B"), 1, 0),
         restrain_flag = if_else(charge_code == "PC" & charge %in% c("166C4", "166D1", "27365A", "6499B"), 1, 0),
         sb10_witness_intim_flag = if_else(charge_code == "PC" & charge %in% c("1361", "1365"), 1, 0),
         sb10_onduty_inel_flag = if_else(charge_code == "PC" & charge %in% c("166", "18626", "18628", "18633", "240", "241", "2411", "2412", "2413",
                                                                             "2414", "2415", "2416", "2417", "2418", "242", "243", "2431", "2432",
                                                                             "24325", "2433", "24335", "2435", "2436", "24365", "2437", "2438",
                                                                             "24383", "2439", "24310", "24315", "2445", "245", "2456", "2463", "247",
                                                                             "2475","248", "120215", "12022A", "12022B", "12022C", "120222A",
                                                                             "120223B", "120225", "653M"), 1, 0),
         property_flag = if_else(jbsis_code %in% c("220", "70"), 1, 0),
         drug_flag = if_else(jbsis_code %in% c("230", "80"), 1, 0),
         minor_flag = if_else(charge %in% c("fix this"), 1, 0),
         pre_arr_inel_flag = if_else(charge %in% c("fix this"), 1, 0)) %>%
  mutate_at(vars(contains("flag")), funs(if_else(is.na(.), 0, as.numeric(.))))

save(charge_hier, file = "Complete Charge Code Hierarchy_SL.RData")

# write.xlsx(charge_hier, file = "G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/Complete Charge Hieararchy with Flags_SL.xlsx", asTable = T, tableStyle = "TableStyleMedium1")
```


Lawyer Reviewed Flags and fix JBSIS codes
```{r}
file <- "G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/Legal Review of Offense Flags.xlsx"

# getSheetNames(file)


df_list <- lapply(c(2:4, 6:22), function(i){
  df <- read_excel(file, sheet = i) %>%
    mutate_all(as.character)
  
  names(df) <- tolower(names(df))
  
  return(df)
})


charge_df <- bind_rows(df_list)

charge_df <- charge_df %>%
  mutate_all(funs(if_else(is.na(.), "0", .))) %>%
  mutate(wrong_offense = if_else(wrong_offense == "1" & grepl("Already captured|repealed|extra numbers", notes), 
                                 "0", 
                                 wrong_offense),
         dv_possible_flag = if_else(grepl("DV depending", notes), "1", "0"),
         charge_level = if_else(charge_level == "0", "Other", charge_level),
         join_var = if_else(!grepl("_.*_", join_var), paste(charge_level, charge_code, charge, sep = "_"), join_var)) %>% 
  select(-c(charge_level, charge_code, charge)) %>%
  separate(join_var, c("charge_level", "charge_code", "charge"), sep = "_", remove = F) %>% 
  filter(wrong_offense != "1") %>%
  select(-contains("notes"), -`sarah review`, -not_charge, -wrong_offense, -missing_offense) %>%
  group_by(join_var) %>%
  mutate_at(vars(hierarchy, jbsis_code, contains("flag")), parse_number) %>%
  summarise_all(max) 
  

load("Complete Charge Code Hierarchy_SL.RData")

#need to fix: some of the lawyer flagged missing charges are in a different format (missing the underscore on the join_var) and therefore are not joining properly

#Putting on lawyer reviewed flags
match_df <- charge_hier %>%
  select(join_var, summary_code, bcs_code) %>%
  inner_join(charge_df, by = "join_var")

match_df2 <- charge_hier %>%
  select(join_var:jbsis_code, summary_code, bcs_code) %>%
  anti_join(charge_df, by = "join_var") 
  
match_df3 <- charge_df %>%
  anti_join(charge_hier, by = "join_var") 

charge_hier <- bind_rows(match_df, match_df3, match_df2) %>%
  distinct(join_var, .keep_all = T) %>%
  mutate_at(vars(contains("flag")), funs(if_else(is.na(.), 0, .))) %>%
  select(-contains("sb10"))



#Fixing missing JBSIS Codes
doj_hierarchy_2020_jbsis <- read_excel("G:/CrimJustice/PretrialAssessmentPilot/Charge Definitions and Hierarchy/2020_March04_DOJ_Offense_Table_JBSIS.xlsx")

names(doj_hierarchy_2020_jbsis) <- c("summary_code", "bcs_code", "hierarchy", "charge_level", "charge", "charge_code", "master_charge_description", "sentence", "jbsis_code")

doj_hierarchy_2020_jbsis <- doj_hierarchy_2020_jbsis %>%
  mutate(charge_level = toupper(charge_level),
         charge_level = if_else(!charge_level %in% c("F", "I", "M"), "Other", charge_level),
         charge = toupper(gsub("\\/|\\(|\\)| |\\.|\\.*|^[A-Z]*|\\\\.*|\\{|\\}|EX|\\+|","", charge)),
         charge_code = if_else(!charge_code %in% c("PC", "VC", "HS", "BP", "WI", "US"), "Other", charge_code)) %>%
  distinct(charge, charge_code, charge_level, .keep_all = T) %>%
  unite(join_var, charge_level, charge_code, charge, remove = F) %>%
  select(join_var, jbsis_code)


charge_hier <- charge_hier %>%
  select(-jbsis_code) %>%
  #Fixing a few codes manually that didn't match on to the DOJ data. We selected the top 7 codes which were not matched.
  left_join(doj_hierarchy_2020_jbsis, by = "join_var") %>%
  mutate(jbsis_code = if_else(join_var == "M_HS_113641A", 230, jbsis_code),
         jbsis_code = if_else(join_var == "M_PC_484488", 220, jbsis_code),
         jbsis_code = if_else(join_var == "M_BP_4140", 230, jbsis_code),
         jbsis_code = if_else(join_var == "F_PC_12020A", 90, jbsis_code),
         jbsis_code = if_else(join_var == "F_PC_45736", 90, jbsis_code))


# Updated 1/7/2021 to match jbsis codes to charges with missing jbsis codes determined by the base charge, when there is no conflict of jbsis codes.
# SB 10 flags are also removed due to its failure. 
charge_hier <- charge_hier %>%
  mutate(charge_start = as.integer(parse_number(charge)),
         jbsis_code = if_else(is.na(jbsis_code)|jbsis_code == 0, 1000, jbsis_code)) %>%
  group_by(charge_level, charge_code, charge_start) %>%
  mutate(n = sum(!(unique(jbsis_code) %in% c(1000, 90, 250, 270)))) %>%
  mutate(jbsis_code = if_else(jbsis_code == 1000 & n %in% 0:1, min(jbsis_code), jbsis_code)) %>%
  ungroup() %>%
  mutate(#Fixing property and drug jbsis flagsdd
         property_flag = if_else(jbsis_code %in% c("220", "70"), 1, 0),
         drug_flag = if_else(jbsis_code %in% c("230", "80"), 1, 0)) %>%
  select(-n) %>%
  mutate(summary_code = if_else(is.na(summary_code), 1000, summary_code))

save(charge_hier, file = "Complete Charge Code Hierarchy_SL.RData")

#save(charge_hier, file = "G:/CrimJustice/PretrialAssessmentPilot/Complete Charge Code Hierarchy_SL.RData")


```

