---
title: "R Notebook"
output: html_notebook
---

# Settup and Library
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_knit$set(root.dir = "G:/CrimJustice/PretrialAssessmentPilot")

# library(rlang)
library(tidyverse)
library(data.table)
library(openxlsx)
library(readxl)
library(lubridate)
library(gsubfn)
library(fuzzyjoin)
library(dplyr)
library(openxlsx)
library(fuzzyjoin)
# library(multidplyr)
#library(pROC)
library(broom)
```

# Data Import --- uhhhhhhh this is weird? Not sure why we have this
```{r eval=FALSE, include=FALSE}
load("G:/CrimJustice/PretrialAssessmentPilot/Final Failure Evaluation2.RData")

eval_df <- eval_df %>%
  filter(new_arrest_flag == 1) %>%
  mutate(arrest_charge_level = case_when(is.na(arrest_charge_level)|arrest_charge_level %in% c("Other", "I") ~"Other_Unknown",
                                         arrest_charge_level == "F" ~ "Felony",
                                         arrest_charge_level == "M" ~ "Misdemeanor")) %>%
  filter(!is.na(cii)) %>%
  mutate(monitor_level = case_when(
    monitor_level %in% c("Level I - Pretrial Release Supervision",
                                     "Pretrial Supervision Level I", "1", "Low") ~ "Low",
    monitor_level %in% c("Level II - Pretrial Release Supervision",
                                     "Pretrial Supervision Level II", "2", "Medium") ~ "Medium",
    monitor_level %in% c("Level III - Pretrial Release Supervision",
                                     "Pretrial Supervision Level III", "3:4", "High") ~ "High",
                              T ~ monitor_level)) %>%
  mutate(fta_flag = if_else(fta_flag == 1|arrest_fta_flag == 1|court_fta_flag == 1|court_fta_flag_doj == 1, 1, 0),
         revoked_flag = if_else(pretrial_termination_outcome == "Unsuccessful", 1, 0),
         oras_risk_score = if_else(oras_risk_score == -Inf, NA_real_, oras_risk_score)) %>%
  mutate(monitor_level = factor(monitor_level, levels = c("Low", "Medium", "High", "Other_Unknown"))) %>%
  mutate(county = tools::toTitleCase(gsub("_", " ", county))) %>%
  mutate(pre_trial_release_flag = if_else(release_date >= pretrial_end_date|is.na(release_date), 0, 1)) %>%
  mutate(sex = case_when(sex == "F" ~ "Female",
                         sex == "M" ~ "Male",
                         T ~ sex),
         tool_name = gsub("-", "", tool_name),
         tool_name = if_else(county == "Alameda" & !is.na(assessment_date), "vprair", tool_name),
         tool_name = if_else(county == "Yuba" & !is.na(assessment_date), "oras", tool_name),
         tool_name = if_else(tool_name == "ORASPAT", "oras", tolower(tool_name)),
         tool_name = if_else(tool_name == "null", NA_character_, tool_name)) %>%
  mutate(release_type = case_when(
    county %in% c("San Joaquin", "Ventura", "Alameda", "Tuolumne", "Nevada", "San Mateo", "Kings") &
      release_type_original %in% c("EMERGENCY ZERO BAIL", "Zero Bail", "TEMPORARY EMERGENCY BAIL",
                                   "TEMPORARY EMERGENCY CITATION", "Covid 19", "Emergency Bail Schedule",
                                   "ZERO DOLLAR BAIL", "COVID-Pretrial Court-Order", "Pandemic Citation Release", 
                                   "Pandemic Sentence Release", "Emergency Bail Schedule-Cite", 
                                   "Emergency Bail Schedule-Court") ~ "Zero_Bail",
    county %in% c("San Joaquin", "Ventura", "Alameda", "Tuolumne", "Nevada", "San Mateo", "Kings") & 
      release_type == "Bail_Bond" ~ "Non_Zero_Bail",
    (!county %in% c("San Joaquin", "Ventura", "Alameda", "Tuolumne", "Nevada", "San Mateo", "Kings")) & 
      release_type == "Bail_Bond" ~ "Unknown_Bail",
    T ~ release_type),
    any_pretrial_failure_flag = if_else(fta_flag == 1|recid_arrested_flag==1|recid_filed_flag==1|recid_convicted_flag==1, 1, 0)) %>%
  mutate(dob = as_date(dob),
         assessment_date = as_date(assessment_date)) %>%
  mutate(age = year(assessment_date) - year(dob),
         age = if_else(month(assessment_date) < month(dob), age - 1L, age),
         age = if_else(month(assessment_date) == month(dob) & day(assessment_date) < day(dob), age - 1L, age),
         age = case_when(age <= 25 & age >= 18 ~ "18-25",
                         age <= 35 & age >= 26 ~ "26-35",
                         age <= 45 & age >= 36 ~ "36-45",
                         age <= 55 & age >= 46 ~ "46-55",
                         age >= 56 & age <= 120 ~ "56+",
                         T ~ "Other_Unknown")) %>%
  mutate_at(vars(contains("flag")), funs(if_else(. == -Inf, 0, .))) %>%
  mutate(release_to_pretrial_end = pretrial_end_date - release_date)

eval_df <- eval_df %>%
  filter(!is.na(assessment_date)) %>%
  # count(tool_name)
  # filter(!is.na(tool_name))
  filter(tool_name %in% c("oras", "psa", "vprai", "vprair", "ccat", "vpraio")) %>%
  filter((psa_nca_risk_score %in% c(1:6) &
         psa_fta_risk_score %in% c(1:6))|tool_name != "psa") %>%
  mutate(oras_risk_score = case_when(
    oras_risk_score %in% 6:9 ~ 3,
    oras_risk_score %in% 3:5 ~ 2,
    oras_risk_score %in% 0:2 ~ 1,
    T ~ NA_real_)) %>%
  mutate(vprai_risk_score = case_when(
    vprai_risk_score %in% 0:1 ~ 1,
    vprai_risk_score %in% 2 ~ 2,
    vprai_risk_score %in% 3 ~ 3,
    vprai_risk_score %in% 4 ~ 4,
    vprai_risk_score %in% 5:9 ~ 5,
  T ~ NA_real_)) %>%
  mutate(vprair_risk_score = case_when(
    vprair_risk_score %in% 0:2 ~ 1,
    vprair_risk_score %in% 3:4 ~ 2,
    vprair_risk_score %in% 5:6 ~ 3,
    vprair_risk_score %in% 7:8 ~ 4,
    vprair_risk_score %in% 9:10 ~ 5,
    vprair_risk_score %in% 11:14 ~ 6,
    T ~ NA_real_))

# Sonoma Fix
load("G:/CrimJustice/PretrialAssessmentPilot/Agency Collapse CSV Files/Sonoma Join Collapse.RData")

sonoma_fix <- sonoma_collapse %>%
  filter(!is.na(psa_nvca_risk_score)) %>%
  distinct(book_num, psa_nvca_risk_score) %>%
  mutate(book_num = as.character(book_num)) %>%
  mutate(county = "Sonoma")

eval_df <- eval_df %>%
  left_join(sonoma_fix, by = c("county", "book_num")) %>%
  # select(contains("psa_nvca_risk_score")) %>%
  mutate(psa_nvca_risk_score = if_else(is.na(psa_nvca_risk_score.x), psa_nvca_risk_score.y, psa_nvca_risk_score.x)) %>%
  select(-psa_nvca_risk_score.x, -psa_nvca_risk_score.y)

save(eval_df, file = "Tool Validation Final Data Frame.RData")
```

# This seems like the relevant part?
Extract and Rename Variables Needed to Load into ADLS and Test Process
```{r}

#load ("G:/CrimJustice/PretrialAssessmentPilot/Tool Validation Final Data Frame.RData")
load("All with recid 6.17.22.RData")

test_doj <- all_with_doj_and_recid %>%
    mutate_at(vars(contains("flag")), funs(if_else(. == -Inf, 0, .))) %>%
  select(county, cii, booking_id, booking_key, booking_date, release_date, case_filed_date, arrest_date, disp_date, sentence_date, case_disposition_date, pretrial_period_end_date, pretrial_period_end_date_doj, filed_flag, convicted_flag, court_disp_flag, court_special_flag, court_serious_felony_flag, court_violent_felony_flag, court_violent_psa_flag, court_capital_flag, court_dv_flag, court_marijuana_flag, court_sup_vio_flag, court_fta_flag, court_sex_flag, court_dui_flag, court_restrain_flag, court_property_flag, court_drug_flag, court_dv_possible_flag, conviction_special_flag, conviction_serious_felony_flag, conviction_violent_felony_flag, conviction_violent_psa_flag, conviction_capital_flag, conviction_dv_flag, conviction_marijuana_flag, conviction_sup_vio_flag, conviction_fta_flag, conviction_sex_flag, conviction_dui_flag, conviction_restrain_flag,conviction_property_flag, conviction_drug_flag, conviction_dv_possible_flag, recid_date, recid_join_var, recid_charge_description, recid_arrested_flag, recid_filed_flag, recid_convicted_flag, recid_arrest_disp_flag, recid_filed_disp_flag, recid_arrest_special_flag, recid_arrest_serious_felony_flag, recid_arrest_violent_felony_flag, recid_arrest_violent_psa_flag, recid_arrest_capital_flag, recid_arrest_dv_flag, recid_arrest_marijuana_flag, recid_arrest_sup_vio_flag, recid_arrest_fta_flag, recid_arrest_sex_flag, recid_arrest_dui_flag, recid_arrest_restrain_flag, recid_arrest_property_flag, recid_arrest_drug_flag, recid_arrest_dv_possible_flag,
recid_filed_special_flag, recid_filed_serious_felony_flag, recid_filed_violent_felony_flag, recid_filed_violent_psa_flag,recid_filed_capital_flag, recid_filed_dv_flag, recid_filed_marijuana_flag, recid_filed_sup_vio_flag, recid_filed_fta_flag, recid_filed_sex_flag, recid_filed_dui_flag, recid_filed_restrain_flag, recid_filed_property_flag, recid_filed_drug_flag, recid_filed_dv_possible_flag, recid_conviction_special_flag, recid_conviction_serious_felony_flag, recid_conviction_violent_felony_flag, recid_conviction_violent_psa_flag, recid_conviction_capital_flag, recid_conviction_dv_flag, recid_conviction_marijuana_flag, recid_conviction_sup_vio_flag, recid_conviction_fta_flag, recid_conviction_sex_flag, recid_conviction_dui_flag, recid_conviction_restrain_flag, recid_conviction_drug_flag, recid_conviction_property_flag, recid_conviction_dv_possible_flag) %>%
rename_all(~str_c(.x,"_DOJ")) %>%
rename_with(~gsub("_DOJ", "", .x), .cols = c(county_DOJ, booking_id_DOJ, booking_key_DOJ, booking_date_DOJ, release_date_DOJ, case_filed_date_DOJ, case_disposition_date_DOJ, pretrial_period_end_date_DOJ)) %>%
rename(pretrial_period_end_date_doj = pretrial_period_end_date_doj_DOJ) %>%
rename(case_disposition_date_doj = disp_date_DOJ) %>%
#rename_with(~str_c(.x,"_DOJ"),.cols = contains("RECID")) %>%
#rename_with(~str_c(.x,"_DOJ"), .cols = c(arrest_date, sentence_date,filed_flag, convicted_flag, court_disp_flag)) %>%
#rename(Booking_date=book_date) %>%
#rename(Case_filed_date=file_date) %>%
#rename(Case_disposition_date=disposition_date) %>%  
#rename(Pretrial_Period_End_Date=pretrial_end_date)  %>%
#rename(Booking_ID=book_num) %>%
#mutate(Pretrial_Period_End_Date_DOJ=Pretrial_Period_End_Date, Case_disposition_date_DOJ=Case_disposition_date, Booking_key=Booking_ID) %>%
rename_all(toupper)   %>%
mutate(CII = CII_DOJ)

fwrite(test_doj, file="G:/CrimJustice/PretrialAssessmentPilot/ADLS Load/test_doj_fw 6.17.22.csv")
save(test_doj, file = "G:/CrimJustice/PretrialAssessmentPilot/ADLS Load/final_doj_for_upload to sf 6.17.22")

all_with_doj_and_recid %>%
  select(contains("disposition"))
 
test_doj
```

Diagnostics
```{r eval=FALSE, include=FALSE}
outcome_df <- test_doj %>%
  rename_all(tolower) %>%
  group_by(county) %>%
  summarise_at(vars(recid_arrested_flag_doj, recid_filed_flag_doj, recid_convicted_flag_doj, 
                    recid_arrest_violent_psa_flag_doj), 
                    # any_pretrial_failure_flag),
               funs(round(mean(.)*100, 1)))

names(outcome_df) <- c("County", "New Arrest", "New Filing", "New Conviction", "New Violent Arrest") 
                       # "FTA or New Arrest")

outcome_df %>%
  filter(County == "Los Angeles")

outcome_df
```
```{r}
test_doj %>%
  rename_all(tolower) %>%
  count(county)
```


```{sql connection=con, include=FALSE, output.var='agg_doj'}
SELECT *
FROM "DWH_PROD"."REPORTING"."AGG_PRETRIAL_KPI_DOJ_ENHANCED"
where cii is not null
;
```

```{r}
outcome_df2 <- agg_doj %>%
  rename_all(tolower) %>%
  mutate(across(c(recid_arrested_flag_doj, recid_filed_flag_doj, recid_convicted_flag_doj, 
                    recid_arrest_violent_psa_flag_doj), ~if_else(is.na(.x), 0, as.numeric(.)))) %>%
  group_by(county) %>%
  summarise_at(vars(recid_arrested_flag_doj, recid_filed_flag_doj, recid_convicted_flag_doj, 
                    recid_arrest_violent_psa_flag_doj), 
                    # any_pretrial_failure_flag),
               funs(round(mean(.)*100, 1)))

names(outcome_df2) <- c("County", "New Arrest", "New Filing", "New Conviction", "New Violent Arrest") 
                       # "FTA or New Arrest")

outcome_df2

agg_doj %>%
  rename_all(tolower) %>%
  group_by(county) %>%
  mutate(across(c(recid_arrested_flag_doj, recid_filed_flag_doj, recid_convicted_flag_doj, 
                    recid_arrest_violent_psa_flag_doj), ~if_else(is.na(.x), 0, as.numeric(.)))) %>%
  select(recid_arrested_flag_doj, recid_filed_flag_doj, recid_convicted_flag_doj, 
                    recid_arrest_violent_psa_flag_doj)
  
                
outcome_df2 %>%
  filter(County == "Los Angeles")

difs <- outcome_df2 %>%
  rename_with(~str_c(.x, " OLD"), .cols = c(-County)) %>%
  left_join(outcome_df %>%
              rename_with(~str_c(.x, " NEW"), .cols = c(-County))) %>%
  mutate(`New Arrest DIF` = `New Arrest NEW` - `New Arrest OLD`) %>%
  mutate(`New Filing DIF` = `New Filing NEW` - `New Filing OLD`) %>%
  mutate(`New Conviction DIF` = `New Conviction NEW` - `New Conviction OLD`) %>%
  mutate(`New Violent Arrest DIF` = `New Violent Arrest NEW` - `New Violent Arrest OLD`) %>%
  select(County, `New Arrest OLD`, `New Arrest NEW`, `New Arrest DIF`, `New Filing OLD`, `New Filing NEW`, `New Filing DIF`, `New Conviction OLD`, `New Conviction NEW`, `New Conviction DIF`,  `New Violent Arrest OLD`, `New Violent Arrest NEW`, `New Violent Arrest DIF`) %>%
  arrange(desc(`New Arrest DIF`))

difs

fwrite(difs, file="G:/CrimJustice/PretrialAssessmentPilot/expected changes with new doj match 6.17.22.csv")
```

```{r}
agg_doj %>%
  rename_all(tolower) %>%
  count(county)
```

